# Generated by Django 5.1.3 on 2024-11-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
    ]
