# Generated by Django 5.1.3 on 2024-11-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('it_manager', 'IT Manager'), ('accountant', 'Accountant'), ('ceo', 'CEO')], max_length=50, null=True)),
                ('section', models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('arcade', 'Arcade'), ('cosmetic_store', 'Cosmetic Store'), ('saloon', 'Saloon'), ('boutique', 'Boutique'), ('spa', 'Spa'), ('lounge', 'Lounge')], max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__worker_id'],
            },
        ),
    ]
