# Generated by Django 5.1.3 on 2024-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_staffprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1 - Limited Access: Can only view assigned section (e.g., Cashier).'), ('2', 'Level 2 - Restricted Access: Can read and modify content within assigned sections (e.g., Manager).'), ('3', 'Level 3 - Read-Only Access: Can view details but cannot edit (e.g., Accountant).'), ('4', 'Level 4 - Full Access: Can read and modify content across all sections (e.g., IT Manager, General Manager, CEO).')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('it_manager', 'IT Manager'), ('general_manager', 'General Manager'), ('accountant', 'Accountant'), ('ceo', 'CEO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='section',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('arcade', 'Arcade'), ('cosmetic_store', 'Cosmetic Store'), ('saloon', 'Saloon'), ('boutique', 'Boutique'), ('spa', 'Spa'), ('lounge', 'Lounge'), ('all', 'All')], max_length=50, null=True),
        ),
    ]
