# Generated by Django 5.1.3 on 2024-11-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0003_remove_game_staff_remove_sale_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
